### ISSUE TITLE
Using VS2015 and FSharp.Core 4.4.0 with Unquote

### ISSUE THREAD

**Issue by darrix** [SwensenSoftware/unquote#119]
Hi, I'm new to Unquote and I'm getting an error when using it with VS2015 and the version of FSharp.Core it installs, 4.4.0.  Is there a configuration tweak I can make to have it use 4.4.0 rather than 4.3.1?

Thanks

**Comment by stephen-swensen** [comment]
Hi -

Yes, you can use a [binding redirect](https://msdn.microsoft.com/en-us/library/eftw1fys%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) from FSharp.Core 4.3.1 to 4.4.0 (NuGet will do this for you automatically if installed from there). That is, you need App.config (or similar, depends on the type of project) file in your project that looks something like the following:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
    </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.4.0.0" newVersion="4.4.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```
