### ISSUE TITLE
Update Unquote site for 3.1.2

### ISSUE THREAD

**Issue by psfblair** [SwensenSoftware/unquote#129]
On http://www.swensensoftware.com/unquote I see 3.1.1 as the latest release, but apparently we have 3.1.2 out now.

**Comment by stephen-swensen** [comment]
@psfblair thanks for the heads up. Question: do you actually use the zip downloads? I am considering stopping doing those and just going NuGet all the way.

**Comment by psfblair** [comment]
No, I was looking at the zip downloads because I was hoping to find a release containing the Expecto support. For my part I would prefer to get the libraries from NuGet.

**Comment by stephen-swensen** [comment]
👍 FYI - I just release version 3.2.0 of Unquote with Expecto support on NuGet

**Comment by stephen-swensen** [comment]
Going ahead and closing this - I won't be providing binary downloads for Unquote going forward, just the NuGet published packages. FYI - you can see release info in the wiki here, which would have also served your purposes: https://github.com/SwensenSoftware/unquote/wiki/ReleaseNotes
