### ISSUE TITLE
Support .NET Standard 2.0

### ISSUE THREAD

**Issue by tlycken** [SwensenSoftware/unquote#130]
Are there any plans to support .NET Standard 1.6? Now that [FsCheck has a .NET Core-compatible build out](https://github.com/fscheck/FsCheck/issues/364), this library is the only thing that I would really miss if I made the switch to .NET Core.

**Comment by stephen-swensen** [comment]
This work is complete. Additionally we will be deprecating .NET 4.0 and PCL builds, leaving support for .NET 4.5 and now .NET Standard 2.0
