### ISSUE TITLE
Support F# 4.1 Result type

### ISSUE THREAD

**Issue by jbrestan** [SwensenSoftware/unquote#131]
Using Unquote 3.2.0 with FSharp.Core 4.4.1.0 (F# 4.1), the following test
```fsharp
[<Fact>]
let ThisWillFail () =
    let actual: Result<string, string> = Ok "foo"
    test <@ match actual with
            | Ok _ -> true
            | Error _ -> false @>
```

where `Result` is `Microsoft.FSharp.Core.Result`, fails with

> System.NotSupportedException: Evaluation of quotation pattern AddressOf not supported: expression = AddressOf (ValueWithName (Ok "foo", actual))

I think this may be related to the fact that FSharpResult is a multi-case discriminated union struct. I've just started migrating to F# 4.1, so I am really mostly guessing here.

Using this equality check seems to work `test <@ actual = Ok "foo" @>`, but in my actual tests the value in Result cannot have equality, so I need to use match.

**Comment by stephen-swensen** [comment]
@jbrestan super interesting, thanks for reporting!

I expect `FSharpResult` to be a pretty common type in the future of F#, especially within tests like here, so going to give this in high priority.

**Comment by jbrestan** [comment]
Thanks for quick response.

Let me know if you need more details - I've encountered this during relatively large project migration so it's possible something else is the root cause. When I use a custom Result type (just a regular DU with two cases) everything works though (with older 4.4.0.0 FSharp.Core as well as with the latest).

**Comment by dsyme** [comment]
I only looked at this very briefly, but it's vaguely possible there is a bug in F# quotations here  - let me know if that's the case - (I hope no of course...)

**Comment by stephen-swensen** [comment]
Hi @dsyme -

Unquote has [never supported `AddressOf`](https://github.com/SwensenSoftware/unquote/blob/924f2fb063e01288361d85dc24b9881a16e1e507/Unquote/Evaluation.fs#L293) evaluation, so I am not surprised by the exception itself. 

However, I am not sure if it is surprising that a quotation involving pattern matching on a struct union includes an `AddressOf` expression like we have here:

    printfn "%A" 
        <@ match actual with
           | Ok _ -> true
           | Error _ -> false @>

    IfThenElse (UnionCaseTest (AddressOf (ValueWithName (Ok "foo", actual)), Error),
            Value (false), Value (true))

Notably, I get a compiler error on with the following similar pattern match on a struct tuple:

    let actual = struct (0,0)
    let code = 
        <@ match actual with
           | struct (0,0) -> true
           | _ -> false @>

`Error	FS0073	internal error: Unexpected expression shape`

**Comment by dsyme** [comment]
@stephen-swensen Can you add a bug at http://github.com/Microsoft/visualfsharp please?  We'd expect these to both work, thanks

**Comment by stephen-swensen** [comment]
@dsyme done: https://github.com/Microsoft/visualfsharp/issues/3118

**Comment by stephen-swensen** [comment]
Looks like this was fixed by https://github.com/Microsoft/visualfsharp/pull/3227 , closing

**Comment by dsyme** [comment]
@stephen-swensen Thanks for reporting the problem
