### ISSUE TITLE
Url to site is broken

### ISSUE THREAD

**Issue by wallymathieu** [SwensenSoftware/unquote#143]
I get a 404 visiting http://www.swensensoftware.com/unquote : 

```
Not Found

The requested URL /unquote was not found on this server.

Apache/2.4.34 (Ubuntu) Server at www.swensensoftware.com Port 80
```

**Comment by stephen-swensen** [comment]
Thanks for reporting! I've been neglecting swensensoftware.com ... I'll get that link working again, but really the main thing that was ever there was binary downloads for Unquote, and going forward I'm only planning on making Unquote available via NuGet.

**Comment by stephen-swensen** [comment]
Fixed!: http://www.swensensoftware.com/unquote/
