### ISSUE TITLE
Wrong assembly version in Unquote.NetStandard

### ISSUE THREAD

**Issue by artemkv** [SwensenSoftware/unquote#152]
Apprarently [<assembly: AssemblyVersion("5.0.0.0")>] in AssemblyInfo.fs is not respected anymore (https://stackoverflow.com/questions/42138418/equivalent-to-assemblyinfo-in-dotnet-core-csproj).

So the compiled dll that comes out from the build of Unquote.NetStandard has version 1.0.0

![unquote](https://user-images.githubusercontent.com/2313395/65153877-cd56a500-da2a-11e9-830a-648d5b874846.png)
![unquote1](https://user-images.githubusercontent.com/2313395/65153878-cd56a500-da2a-11e9-9ca3-a8f9d7daa3ca.png)

This breaks other packages, like FSharp.AWS.DynamoDB that have Unquote as a dependency, at least when using the paket dependency manager.

When trying to use FSharp.AWS.DynamoDB which depends on Unquote, I am getting the error: `Could not load file or assembly 'Unquote, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

I cloned the repo and updated Unquote.NetStandard.fsproj by adding the following line to PropertyGroup: `<Version>5.0.0</Version>`. Then I re-compiled and manually replaced dll next to my project, then it worked.

Adding `<GenerateAssemblyInfo>false</GenerateAssemblyInfo>` to Unquote.NetStandard.fsproj also produced the dll with the correct version in manifest.

Could you please make sure that Unquote.NetStandard is build with the correct version?

**Comment by stephen-swensen** [comment]
Oh wow, thanks for detailed report! I'll try to get a fix out ASAP.

**Comment by stephen-swensen** [comment]
ASAP can be a long time for me these days... sorry. This is still on my radar though.

**Comment by stephen-swensen** [comment]
This will be fixed by https://github.com/SwensenSoftware/unquote/pull/156

**Comment by stephen-swensen** [comment]
This is now released as part of Unquote 6.0.0! Thanks for your patience. A big part of Unquote 6.0.0 was modernizing build tooling which I hope will improve turn-around time for fixing issues like this including encouraging more contributions by the community.
