### ISSUE TITLE
Default output for DateTime comparisons can be confusing

### ISSUE THREAD

**Issue by thednaz** [SwensenSoftware/unquote#155]
The following test will fail, since the DateTime values will be slightly different.

```[<Theory>]
let ``Test`` =
    let actual = DateTime.UtcNow
    let expected = DateTime.UtcNow
    
    test <@ actual = expected @>`
```
The exception output:
```
actual = expected
10/13/2020 9:36:09 PM = 10/13/2020 9:36:09 PM
false
Expected: True
Actual:   False
```

The issue is, the default output formatting will show the times to be the same, which has confused people. Can default output formats for certain types be overriden, to make the reason for this type of test failure very clear? Or is there another workaround that you can suggest?

**Comment by stephen-swensen** [comment]
Hi - I think we can improve the default output to include higher precision. Unquote doesn't expose a way for user's to override formatting currently.
