### ISSUE TITLE
Format byte output as hex?

### ISSUE THREAD

**Issue by aggieben** [SwensenSoftware/unquote#164]
This is somewhat minor, but is there a way to format the output of a failed test where bytes are in the output so that the bytes are rendered as hex?

**Comment by stephen-swensen** [comment]
Hi @aggieben - we don't currently have a way to pass configuration options for formatting. So the formatting choices we do make we try to make as broadly useful as possible. I don't work with raw bytes / hex a whole lot so I am not sure what would be broadly useful to such an audience (e.g. can we say that hex is usually preferable to decimal when rendering bytes?). I'm open to suggestions and examples but closing for now. Thanks for your question!
