### ISSUE TITLE
Option to print only last step of evaluation

### ISSUE THREAD

**Issue by ursenzler** [SwensenSoftware/unquote#171]
Unquote prints all steps of the evaluation, which is generally great.

We have, however, some tests that check for quite big value-trees and having multiple steps makes reading the error messages very hard.

One improvement could be only to print the last evaluation step. (Maybe the other request to better separate the steps would help as well).

Just to get a feel for it - I didn't take a look at the code yet, how hard would it be to implement something like this?
If it is straightforward, I could find some time to help with this.

**Comment by stephen-swensen** [comment]
Hi - this is similar to this issue where we implemented a `testSimple` assertion: https://github.com/SwensenSoftware/unquote/issues/148

In fact, what you are asking for sounds like "Option B" that was floated (but we went with "Option A", only print the head expression). Maybe this would work for you. If not, it wouldn't be too hard to implement another assertion that does what you are asking for: https://github.com/SwensenSoftware/unquote/commit/d6712d096337446f39773b339ccdf96588e03f1d ... you might try just experimenting with your own custom assertion implementation. I'm a little wary of proliferating variations of "simple" test assertions.

**Comment by ursenzler** [comment]
I finally found time to take a look. It seems this solves my needs:

    let u = unquote expr
    match u.FinalReduction with
    | DerivedPatterns.Bool(true) -> ()
    | _ ->
        if u.Reductions.Length > 2 then
            Assertions.Internal.testFailed [ u.Reductions[u.Reductions.Length - 2]]  ""
        else
            Assertions.Internal.testFailed u.Reductions ""
            
            
Thanks!
