### ISSUE TITLE
Convert .bat build script to FAKE or NAnt and/or MSBuild script

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SwensenSoftware/unquote#74]
```
The .bat build script has gotten pretty crazy, should convert this a NAnt 
and/or MSBuild script
```

Original issue reported on code.google.com by `stephen....@gmail.com` on 28 Nov 2011 at 3:18

**Comment by enricosada** [comment]
@stephen-swensen do you still want a FAKE script? i really like this project :+1: 

just asking because build script is always a personal preference of mantainer, so better ask before send pr.
I think the f# community can help about that.

**Comment by stephen-swensen** [comment]
@enricosada I am still interested in moving to FAKE build script and would greatly appreciate F# community help (but perhaps after we complete .NET Core support PR). 

When I last looked into FAKE, I had some concerns about its ability to build / run tests for different profiles (portable, full .NET, etc.)... a vague recollection, perhaps not a contemporary concern.

(aside: apologies if I have been slow to respond / follow up on your comments / PR... 'been super busy at home and work the past few months, but I am looking to free myself up soon).

**Comment by stephen-swensen** [comment]
Closing this issue as "wont fix": I'm working on the `v6` branch which will fully decouple Unquote from Windows / Visual Studio / .NET traditional and go all the way with `dotnet` tooling with some light Makefile scripting. We will only target .netstandard2.0. Given all that streamlining, our builds will be simple enough that we using FAKE isn't really warranted.
